### ISSUE TITLE
Instructions on using this package with angularjs

### ISSUE THREAD

**Issue by MeghaY** [nathanhammond/libphonenumber#1]
Hello,

Can you include some instructions/steps for adding this 'libphonenumber' module to angularjs project for better understanding? Thanks

**Comment by shailu26** [comment]
i am using gulp, i am importing libphonenumber.js in vendor scripts, how can i use phoneUtils.formatE164 in my controller now?

**Comment by shailu26** [comment]
oh i got it, so phoneUtils was global variable so it was attached in $window so i can access phoneUtils from anywhere like $window.phoneUtils.formatE164. 💯 👍
