### ISSUE TITLE
phoneUtils.getCountryCodeForRegion is not a function

### ISSUE THREAD

**Issue by eupathy** [nathanhammond/libphonenumber#12]
In documentation presnt this function https://github.com/nathanhammond/libphonenumber#exports , but, unlucky, i can't use it. :( I install this lib through bower

**Comment by nathanhammond** [comment]
It works, here is an example: https://jsfiddle.net/LwttLuz4/

Closing.

**Comment by eupathy** [comment]
Thank you for answer.
Yes, realy, it work if i get your library from github, but don't work, if i use bower (bower i libphonenumber). Anycase thanx for this plugin.
