### ISSUE TITLE
only two method are exported

### ISSUE THREAD

**Issue by bogomips** [nathanhammond/libphonenumber#15]
Hi, 
I read from the readme:

phoneUtils.countryCodeToRegionCodeMap();
phoneUtils.isPossibleNumber(phoneNumber, regionCode);
phoneUtils.isPossibleNumberWithReason(phoneNumber, regionCode);
phoneUtils.isValidNumber(phoneNumber, regionCode);
phoneUtils.isValidNumberForRegion(phoneNumber, regionCode);
phoneUtils.getCountryCodeForRegion(regionCode);
phoneUtils.getRegionCodeForNumber(phoneNumber, regionCode);
phoneUtils.getNumberType(phoneNumber, regionCode);
phoneUtils.getSupportedRegions();
phoneUtils.formatE164(phoneNumber, regionCode);
phoneUtils.formatNational(phoneNumber, regionCode);
phoneUtils.formatInternational(phoneNumber, regionCode);
phoneUtils.formatInOriginalFormat(phoneNumber, regionCode);
phoneUtils.formatOutOfCountryCallingNumber(phoneNumber, regionCode, target);

but a simple console.log(phoneUtils) shows this:

formatAsTyped: (a,c)
isValidNumberForRegion: (a,c)

What am I missing?
Thanks.

**Comment by nathanhammond** [comment]
It works: https://jsfiddle.net/406s2u2b/

Closing as invalid.
