### ISSUE TITLE
Getting error when building.

### ISSUE THREAD

**Issue by gitjeff05** [nathanhammond/libphonenumber#16]
Buildfile: /Users/laiosa/github/nathan/libphonenumber/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

What is ``net/sf/antcontrib/antlib.xml`` supposed to do? I noticed that is not in libphonenumber.

**Comment by nathanhammond** [comment]
On OS X: `brew install ant-contrib` ... you must have additional helpers for `foreach` inside of build.xml to do its thing.

Alternatively, the `dist` folder has everything you need in it.
