### ISSUE TITLE
Unsafe parallel execution in build

### ISSUE THREAD

**Issue by theseyi** [nathanhammond/libphonenumber#19]
In the build.xml config file for Ant the foreach task on line 157: 
`<foreach parallel="true" target="compile-country-libphonenumber" param="regioncode" list="${regioncodes}"/>`
it seems, is not safe for parallel execution. 
This task, with `parallel="true"` generates a file name `dist/libphonenumber_US,AG,AI,AS,BB,BM,BS,CA,DM,DO,GD,GU,JM,KN,KY,LC,MP,MS,PR,SX,TC,TT,VC,VG,VI,RU,KZ,EG,ZA,GR,NL,BE,FR,ES,HU,IT,VA,RO,CH,AT,GB,GG,IM,JE,DK,SE,NO,SJ,PL,DE,PE,MX,CU,AR,BR,CL,CO,VE,MY,AU,CC,CX,ID,PH,NZ,SG,TH,JP,KR,VN,CN,TR,IN,PK,AF,LK,MM,IR,SS,MA,EH,DZ,TN,LY,GM,SN,MR,ML,GN,CI,BF,NE,TG,BJ,MU,LR,SL,GH,NG,TD,CF,CM,CV,ST,GQ,GA,CG,CD,AO,GW,IO,AC,SC,SD,RW,ET,SO,DJ,KE,TZ,UG,BI,MZ,ZM,MG,RE,YT,ZW,NA,MW,LS,BW,SZ,KM,SH,TA,ER,AW,FO,GL,GI,PT,LU,IE,IS,AL,MT,CY,FI,AX,BG,LT,LV,EE,MD,AM,BY,AD,MC,SM,UA,RS,ME,HR,SI,BA,MK,CZ,SK,LI,FK,BZ,GT,SV,HN,NI,CR,PA,PM,HT,GP,BL,MF,BO,GY,EC,GF,PY,MQ,SR,UY,CW,BQ,TL,NF,BN,NR,PG,TO,SB,VU,FJ,PW,WF,CK,NU,WS,KI,NC,TV,PF,TK,FM,MH,001,KP,HK,MO,KH,LA,BD,TW,MV,LB,JO,SY,IQ,KW,SA,YE,OM,PS,AE,IL,BH,QA,BT,MN,NP,TJ,TM,AZ,GE,KG,UZ.js`.

This in turn causes python to error out with the file name being too long:
`compile:
compile-country-libphonenumber:
     [exec] Traceback (most recent call last):
     [exec]   File "/temp/vendor/closure-library/closure/bin/calcdeps.py", line 590, in <module>
     [exec]     main()
     [exec]   File "/temp/vendor/closure-library/closure/bin/calcdeps.py", line 545, in main
     [exec]     out = open(options.output_file, 'w')
     [exec] IOError: [Errno 63] File name too long: 'dist/libphonenumber_US,AG,AI,AS,BB,BM,BS,CA,DM,DO,GD,GU,JM,KN,KY,LC,MP,MS,PR,SX,TC,TT,VC,VG,VI,RU,KZ,EG,ZA,GR,NL,BE,FR,ES,HU,IT,VA,RO,CH,AT,GB,GG,IM,JE,DK,SE,NO,SJ,PL,DE,PE,MX,CU,AR,BR,CL,CO,VE,MY,AU,CC,CX,ID,PH,NZ,SG,TH,JP,KR,VN,CN,TR,IN,PK,AF,LK,MM,IR,SS,MA,EH,DZ,TN,LY,GM,SN,MR,ML,GN,CI,BF,NE,TG,BJ,MU,LR,SL,GH,NG,TD,CF,CM,CV,ST,GQ,GA,CG,CD,AO,GW,IO,AC,SC,SD,RW,ET,SO,DJ,KE,TZ,UG,BI,MZ,ZM,MG,RE,YT,ZW,NA,MW,LS,BW,SZ,KM,SH,TA,ER,AW,FO,GL,GI,PT,LU,IE,IS,AL,MT,CY,FI,AX,BG,LT,LV,EE,MD,AM,BY,AD,MC,SM,UA,RS,ME,HR,SI,BA,MK,CZ,SK,LI,FK,BZ,GT,SV,HN,NI,CR,PA,PM,HT,GP,BL,MF,BO,GY,EC,GF,PY,MQ,SR,UY,CW,BQ,TL,NF,BN,NR,PG,TO,SB,VU,FJ,PW,WF,CK,NU,WS,KI,NC,TV,PF,TK,FM,MH,001,KP,HK,MO,KH,LA,BD,TW,MV,LB,JO,SY,IQ,KW,SA,YE,OM,PS,AE,IL,BH,QA,BT,MN,NP,TJ,TM,AZ,GE,KG,UZ.js'`

**Comment by nathanhammond** [comment]
Your list isn't being split. Please see my comment from the other issue you filed. I believe that you don't have `ant-contrib` properly set up.
