### ISSUE TITLE
Updating libphonenumber version

### ISSUE THREAD

**Issue by arturskeeled** [nathanhammond/libphonenumber#27]
Hey, any plans to update libphonenumber to the latest release?
Thanks for the plugin btw :)

**Comment by robsonrosa** [comment]
How could I update libphonenumber to the latest release?
I'm not familiar with maven build, closure compiler and anything else. 
Is there a guide or tutorial? 

With some help, I could update and then do a PR.
I'd love to help!

**Comment by arturskeeled** [comment]
@robsonrosa @nathanhammond 
Someone from my company took care of it, please merge if you'd like 👍 
https://github.com/nathanhammond/libphonenumber/pull/31
